### ISSUE TITLE
tmfs creates a filesystem that is not accessible

### ISSUE THREAD

**Issue by SuperShinyEyes** [abique/tmfs#17]
Environment: 16.04.1-Ubuntu 64 bit

I could mount a sparsebundle image as an HFS following: https://github.com/torarnv/sparsebundlefs
But when I ran

```
sudo  tmfs /mnt/hfs /mnt/tm -ouid=$(id -u $USER),gid=$(id -g $USER),allow_other
```

I got something that is not accessible. I couldn't run `ls`  as it would say `No such file or directory`.

Any idea?

**Comment by coderforlife** [comment]
This seems to happen if you forget that you also have to mount the results of sparsebundlefs as an HFS+ drive.

**Comment by tokenwizard** [comment]
I'm having the same issue (or similar at least)...

Fedora 32 mounts the Data1 partition of the Time Machine disk on its own without issue:
`/dev/sdd3 on /run/media/tokenwizard/Data1 type hfsplus (ro,nosuid,nodev,relatime,umask=22,uid=1000,gid=1000,nls=utf8,uhelper=udisks2)`

Then I use sparsebundlefs to get the sparsebundle.dmg from the partition:
`sudo /home/tokenwizard/bin/sparsebundlefs -o allow_other '/run/media/tokenwizard/Data1/ShareRoot/Tokenwizard.sparsebundle' mnt/sparsebundle-mnt`

Here you can see it mounted:
`/home/tokenwizard/sparsebundlefs on /home/tokenwizard/mnt/sparsebundle-mnt type fuse.sparsebundlefs (ro,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)`

`[tokenwizard@localhost ~]$ ls -l mnt/sparsebundle-mnt/
total 0
-r-----r--. 1 root nobody 998057361408 Mar 10  2019 sparsebundle.dmg`

Now I mount the dmg file as an HFS loop device, per the sparsebundlefs documentation:
`sudo mount -o loop -t hfsplus mnt/sparsebundle-mnt/sparsebundle.dmg mnt/hfs-root`
`/home/tokenwizard/mnt/sparsebundle-mnt/sparsebundle.dmg on /home/tokenwizard/mnt/hfs-root type hfsplus (ro,relatime,umask=22,uid=0,gid=0,nls=utf8)`
`[tokenwizard@localhost ~]$ ls -l mnt/hfs-root
total 0
drwxr-xr-x. 1 root 99 6 Mar  7  2019 Backups.backupdb`

Lastly, I use tmfs to remount that hfs-root for Time Machine filesystem:
`sudo tmfs mnt/hfs-root mnt/tm-root -ouid=$(id -u),gid=$(id -g),allow_other`
`tmfs on /home/tokenwizard/mnt/tm-root type fuse.tmfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)`

But when I try to list the contents of that tm-root mountpoint, it is like it does not exist:
`[tokenwizard@localhost ~]$ ls -l mnt
ls: cannot access 'mnt/tm-root': No such file or directory
total 0
drwxr-xr-x. 1 root root   12 Feb 10  2014 hfs-root
dr-x---r-x. 3 root nobody 96 Mar 10  2019 sparsebundle-mnt
d?????????? ? ?    ?       ?            ? tm-root`

I must be missing something here. Please point me in the right direction.

Thanks!

**Comment by tokenwizard** [comment]
Ok,
I figured it out. I needed to use the full paths with the tmfs command. Apparently it does not like using sudo with relative paths.

So this command gave me a working tm-root:
`sudo tmfs /home/tokenwizard/mnt/hfs-root /home/tokenwizard/mnt/tm-root -ouid=$(id -u),gid=$(id -g),allow_other`

**Comment by iburinoc** [comment]
I created #24 which should fix this.

**Comment by iburinoc** [comment]
#24 was merged so I believe this should be fixed now.

**Comment by abique** [comment]
OK I close the issue.
