### ISSUE TITLE
__S_IFDIR not defined 

### ISSUE THREAD

**Issue by onefastskater** [abique/tmfs#19]
ARKs-Mac-mini:build markriley$ cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

MARKs-Mac-mini:build markriley$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'fuse'
--   Found fuse, version 2.9.7
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/markriley/Mark/personal/GitTimeMachine/tmfs/tmfs-master/build
MARKs-Mac-mini:build markriley$ ls
CMakeCache.txt		CMakeFiles		Makefile		cmake_install.cmake
MARKs-Mac-mini:build markriley$ make
Scanning dependencies of target tmfs
[ 14%] Building CXX object CMakeFiles/tmfs.dir/src/main.cc.o
[ 28%] Building CXX object CMakeFiles/tmfs.dir/src/readdir.cc.o
/Users/markriley/Mark/personal/GitTimeMachine/tmfs/tmfs-master/src/readdir.cc:16:19: error: use of undeclared identifier '__S_IFDIR'
  stbuf.st_mode = __S_IFDIR | 0755;
                  ^
1 error generated.
make[2]: *** [CMakeFiles/tmfs.dir/src/readdir.cc.o] Error 1
make[1]: *** [CMakeFiles/tmfs.dir/all] Error 2
make: *** [all] Error 2

**Comment by abique** [comment]
We now use the std::filesystem library. Please try again.
