### ISSUE TITLE
Missing boost symbols when building on Ubuntu 12.04

### ISSUE THREAD

**Issue by jonasaugust** [abique/tmfs#2]
Hi, tmfs looks very promising in helping me transfer my old Time Machine backup to my Ubuntu box. I'm trying to build tmfs on Ubuntu 12.04, but I'm having trouble.  Specifically, some undefined references come up when making:

---

jonas@P9X79:~/pkg/tmfs/build$ make
Linking CXX executable tmfs
CMakeFiles/tmfs.dir/src/main.cc.o: In function `__static_initialization_and_destruction_0(int, int)':
main.cc:(.text+0x16a): undefined reference to`boost::system::generic_category()'
main.cc:(.text+0x176): undefined reference to `boost::system::generic_category()'
main.cc:(.text+0x182): undefined reference to`boost::system::system_category()'
CMakeFiles/tmfs.dir/src/readdir.cc.o: In function `__static_initialization_and_destruction_0(int, int)':
readdir.cc:(.text+0x351): undefined reference to`boost::system::generic_category()'
readdir.cc:(.text+0x35d): undefined reference to `boost::system::generic_category()'
readdir.cc:(.text+0x369): undefined reference to`boost::system::system_category()'
CMakeFiles/tmfs.dir/src/readdir.cc.o: In function `boost::filesystem3::path::codecvt()':
readdir.cc:(.text._ZN5boost11filesystem34path7codecvtEv[boost::filesystem3::path::codecvt()]+0x5): undefined reference to`boost::filesystem3::path::wchar_t_codecvt_facet()'
CMakeFiles/tmfs.dir/src/readdir.cc.o: In function `boost::filesystem3::operator/(boost::filesystem3::path const&, boost::filesystem3::path const&)':
readdir.cc:(.text._ZN5boost11filesystem3dvERKNS0_4pathES3_[boost::filesystem3::operator/(boost::filesystem3::path const&, boost::filesystem3::path const&)]+0x37): undefined reference to`boost::filesystem3::path::operator/=(boost::filesystem3::path const&)'
CMakeFiles/tmfs.dir/src/readdir.cc.o: In function `boost::filesystem3::is_directory(boost::filesystem3::path const&)':
readdir.cc:(.text._ZN5boost11filesystem312is_directoryERKNS0_4pathE[boost::filesystem3::is_directory(boost::filesystem3::path const&)]+0x19): undefined reference to`boost::filesystem3::detail::status(boost::filesystem3::path const&, boost::system::error_code_)'
CMakeFiles/tmfs.dir/src/read.cc.o: In function `__static_initialization_and_destruction_0(int, int)':
read.cc:(.text+0x187): undefined reference to`boost::system::generic_category()'
read.cc:(.text+0x193): undefined reference to `boost::system::generic_category()'
read.cc:(.text+0x19f): undefined reference to`boost::system::system_category()'
CMakeFiles/tmfs.dir/src/getattr.cc.o: In function `__static_initialization_and_destruction_0(int, int)':
getattr.cc:(.text+0x155): undefined reference to`boost::system::generic_category()'
getattr.cc:(.text+0x161): undefined reference to `boost::system::generic_category()'
getattr.cc:(.text+0x16d): undefined reference to`boost::system::system_category()'
CMakeFiles/tmfs.dir/src/get_real_path.cc.o: In function `get_real_path(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
get_real_path.cc:(.text+0x5e): undefined reference to`boost::filesystem3::absolute(boost::filesystem3::path const&, boost::filesystem3::path const&)'
get_real_path.cc:(.text+0xc1): undefined reference to `boost::filesystem3::path::begin() const'
get_real_path.cc:(.text+0xe3): undefined reference to`boost::filesystem3::path::end() const'
get_real_path.cc:(.text+0x158): undefined reference to `boost::filesystem3::path::operator/=(boost::filesystem3::path const&)'
get_real_path.cc:(.text+0x1a0): undefined reference to`boost::filesystem3::path::operator/=(boost::filesystem3::path const&)'
get_real_path.cc:(.text+0x32a): undefined reference to `boost::filesystem3::path::end() const'
CMakeFiles/tmfs.dir/src/get_real_path.cc.o: In function`__static_initialization_and_destruction_0(int, int)':
get_real_path.cc:(.text+0x4d1): undefined reference to `boost::system::generic_category()'
get_real_path.cc:(.text+0x4dd): undefined reference to`boost::system::generic_category()'
get_real_path.cc:(.text+0x4e9): undefined reference to `boost::system::system_category()'
CMakeFiles/tmfs.dir/src/get_real_path.cc.o: In function`boost::filesystem3::path::iterator::increment()':
get_real_path.cc:(.text._ZN5boost11filesystem34path8iterator9incrementEv[boost::filesystem3::path::iterator::increment()]+0x14): undefined reference to `boost::filesystem3::path::m_path_iterator_increment(boost::filesystem3::path::iterator&)'
CMakeFiles/tmfs.dir/src/get_real_path.cc.o: In function`boost::filesystem3::path& boost::filesystem3::path::append<char [17]>(char const (&) [17], std::codecvt<wchar_t, char, __mbstate_t> const&)':
get_real_path.cc:(.text._ZN5boost11filesystem34path6appendIA17_cEERS1_RKT_RKSt7codecvtIwc11__mbstate_tE[boost::filesystem3::path& boost::filesystem3::path::append<char [17]>(char const (&) [17], std::codecvt<wchar_t, char, __mbstate_t> const&)]+0x36): undefined reference to `boost::filesystem3::path::m_append_separator_if_needed()'
get_real_path.cc:(.text._ZN5boost11filesystem34path6appendIA17_cEERS1_RKT_RKSt7codecvtIwc11__mbstate_tE[boost::filesystem3::path& boost::filesystem3::path::append<char [17]>(char const (&) [17], std::codecvt<wchar_t, char, __mbstate_t> const&)]+0xa6): undefined reference to`boost::filesystem3::path::m_erase_redundant_separator(unsigned long)'
collect2: ld returned 1 exit status
make[2]: *_\* [tmfs] Error 1
make[1]: **\* [CMakeFiles/tmfs.dir/all] Error 2
make: **\* [all] Error 2

---

To prepare for installing tmfs on my system, I first did:

sudo apt-get install libboost-all-dev cmake libfuse-dev

This seems to have installed libboost-system-dev.  

Also, g++ version 4.6.3 is installed.

Any ideas of what Ubuntu package I'm missing?  I'm really hoping I won't have to install boost from scratch.

**Comment by jameswalmsley** [comment]
I also came across this issue, the problem was the the original build folder was generated before the following package was installed:

sudo apt-get install libboost-all-dev

The cmake system only finds the boost libraries when their respective -dev packages are installed.

**Comment by riccardocossu** [comment]
I also solved by removing the build directory, installing libbost-all-dev and rebuilding by scratch
