### ISSUE TITLE
Does it support only HFS as a base files system?

### ISSUE THREAD

**Issue by Compound** [abique/tmfs#8]
I got a volume which is based on ext4. It includes my TimeMachine backup. Can I access this TimeMachine backup with tmfs?

Thanks.

**Comment by coderforlife** [comment]
I was wondering about this as well, and you first have to mount the sparsebundle using the sparsebundlefs (https://github.com/torarnv/sparsebundlefs) and then you can use the tmfs on top of that.

For more details see https://superuser.com/a/487454/63868

**Comment by abique** [comment]
If any of you feel like writing a few lines in the readme that'd be welcome :)
